### PR TITLE
feat(infra): avoided error messages in repeated installations

### PR DESCRIPTION
**Pull request by jonrkarr**
Closes https://formiclabs.atlassian.net/browse/DOS-1752

### CODE REVIEW

**Review by sg-s — COMMENTED** [review]
doesn't work for me:

```
mkdir: illegal option -- -
usage: mkdir [-pv] [-m mode] directory_name ...
make: [Makefile:32: install] Error 64 (ignored)
if [ ! -f ~/.deeporigin/deeporigin ]; then
/bin/bash: -c: line 1: syntax error: unexpected end of file
make: *** [Makefile:33: install] Error 2
```

**Comment by sg-s** [comment]
IMO having errors (ignored) in a makefile is idiomatic and the logic you're putting in here is already handled by the `-` operator

**Comment by jonrkarr** [comment]
> doesn't work for me:

Fixed. I assumed bash syntax would work and didn't check.

**Comment by jonrkarr** [comment]
> IMO having errors (ignored) in a makefile is idiomatic and the logic you're putting in here is already handled by the `-` operator

To me, I found output confusing because it looks like an unhandled error when the program skipped creating a new directory and adding a symlink, as expected. I would be more inclined to agree if the errors were reported as warnings. Something more like:
```
1 warning was found
-----------------------
warning >> mkdir: cannot create directory ‘/home/jonrkarr/.deeporigin’: File exists
warning >> make: [Makefile:32: install] Error 1 (ignored)
warning >> ln: failed to create symbolic link '/home/jonrkarr/.deeporigin/deeporigin': File exists
warning >> make: [Makefile:33: install] Error 1 (ignored)
```

**Comment by sg-s** [comment]
yeah, that's just the way make works

**Review by sg-s — APPROVED** [review]

**Pull request merged**
